version: "3"

services:
    wx-box:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: "wx-box"
        environment:
            VNC_PASSWORD: "1"
        ports:
            - "8080:8080"
        volumes:
            - "./WeChat_Files/:/root/WeChat Files/"        
        tty: true