common:
  log_level: info
  is_prod: true

httpd:
  addr: 0.0.0.0:80
  enable: true

rpc:
  host: localhost
  port: 8888
  enable: true

callbacks:
  download_file:
    enable: true
  auto_accept_friend_invite:
    enable: true
  echo:
    enable: true
