common:
  log_level: info
  is_prod: true

database:
  user: root
  password: mysqlpwd
  host: mysql
  port: 3306
  database: wx

httpd:
  addr: 0.0.0.0:80
  enable: true

rpc:
  host: localhost
  port: 8888
  enable: true

callbacks:
  save_message:
    enable: true
  auto_accept_friend_invite:
    enable: true
  echo:
    enable: true
